---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2023: true
globals:
  sap: false
  SELECT: false
  INSERT: false
  UPDATE: false
  DELETE: false
  CREATE: false
  DROP: false
  STREAM: false
plugins:
  - jest
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  no-unused-vars: [off]
  require-atomic-updates: [off]
  jest/no-conditional-expect: [off]
  jest/no-disabled-tests: [off]
  jest/expect-expect: [off]
  no-restricted-modules: [error, child_process] # security
  no-eval: [error] # security
  no-implied-eval: [error] # security
  no-console: [error] # ops
  no-useless-escape: [off]
  strict: [off]
  curly: [error]
  no-constant-condition: [error, { checkLoops: false }]
  no-prototype-builtins: off
  "@typescript-eslint/no-unused-vars": [off]
  "@typescript-eslint/no-var-requires": [off]
