---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2017: true
parserOptions:
  ecmaVersion: 8
globals:
  sap: false
  SELECT: false
  INSERT: false
  UPDATE: false
  DELETE: false
  CREATE: false
  DROP: false
plugins:
  - jest
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - prettier
rules:
  no-console: [off]
  no-unused-vars: [off]
  require-atomic-updates: [off]
